### ISSUE TITLE
Reading from process.stdin.fd raises EAGAIN

### ISSUE THREAD

**Issue by davedoesdev** [devsnek/node-wasi#8] opened 2019-05-27 07:18 UTC
I was having problems reading from stdin in C++. Changing `process.stdin.fd` in `index.js` to `0` fixes this. You can repro using this simple test program:

```javascript
const fs = require('fs');
const buf = Buffer.alloc(1024);
console.log(fs.readSync(process.stdin.fd, buf, 0, buf.length));
```

I made a similar change for `process.stdout.fd` and `process.stderr.fd`. Basically you can't access `process.std*` without affecting file descriptor reads.

**Comment by devsnek** [comment] 2019-05-27 15:08
eagain means there's no data available and that you should try to read later. are you sure you are giving stdin data?

**Comment by davedoesdev** [comment] 2019-05-27 22:39
Ah, it's because the library I'm using is doing:

```c++
std::streambuf& sb(*std::cin.rdbuf());
auto ch = sb.sbumpc();
```

**Comment by davedoesdev** [comment] 2019-05-27 22:40
I guess this might be an issue for wasi-sysroot

**Comment by davedoesdev** [comment] 2019-05-27 23:11
For me, the existing stdin test fails if I modify it to check the return codes:

```diff
diff --git a/test/c/stdin.c b/test/c/stdin.c
index 137a447..8cbf21e 100644
--- a/test/c/stdin.c
+++ b/test/c/stdin.c
@@ -4,7 +4,9 @@ int main(void)
 {
     char x[32];
 
-    fgets(x, sizeof x, stdin);
+    if (!fgets(x, sizeof x, stdin)) {
+        return 1;
+    }
     fputs(x, stdout);
     return 0;
 }
```

I'm on Ubuntu 19.04, running `npm test` from a terminal.

I also notice that `read()` fails.

**Comment by davedoesdev** [comment] 2019-05-27 23:12
```
> wasi@0.0.4 test /tmp/wup/node-wasi
> node test/run.js

cant_dotdot
clock_getres
exitcode
follow_symlink
getentropy
getrusage
gettimeofday
notdir
preopen_populates
read_file
read_file_twice
stdin
/tmp/wup/node-wasi/test/run.js:48
    throw new Error(`${file}: exit ${code}`);
    ^

Error: stdin: exit 1
    at /tmp/wup/node-wasi/test/run.js:48:11
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/tmp/wup/node-wasi/test/run.js:32:7)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
npm ERR! Test failed.  See above for more details.
```

**Comment by davedoesdev** [comment] 2019-05-27 23:30
Hmm, I think that's because `test/run.js` doesn't pass any stdin down. With this change it passes:

```diff
diff --git a/test/run.js b/test/run.js
index c02248c..d47a0cb 100755
--- a/test/run.js
+++ b/test/run.js
@@ -13,13 +13,8 @@ const C_DIR = path.resolve(__dirname, 'c');
 const OUT_DIR = path.resolve(__dirname, 'out');
 const RUNNER_PATH = path.resolve(__dirname, 'runner.js');
 
-function exec(command) {
-  try {
-    cp.execSync(command);
-    return 0;
-  } catch (e) {
-    return e.status;
-  }
+function exec(command, ...args) {
+  return cp.spawnSync(command, args, { input: 'foo' }).status;
 }
 
 function cleanup() {
@@ -40,9 +35,9 @@ files.forEach((filename) => {
 
   cleanup();
 
-  exec(`/opt/wasi-sdk/bin/clang ${C_DIR}/${filename} -target wasm32-unknown-wasi -o ${OUT_DIR}/${file}.wasm`);
+  exec('/opt/wasi-sdk/bin/clang', `${C_DIR}/${filename}`, `-target`, `wasm32-unknown-wasi`, `-o`, `${OUT_DIR}/${file}.wasm`);
 
-  const code = exec(`node --experimental-wasm-bigint ${RUNNER_PATH} ${OUT_DIR}/${file}.wasm`);
+  const code = exec('node', '--experimental-wasm-bigint', `${RUNNER_PATH}`, `${OUT_DIR}/${file}.wasm`);
 
   if (code !== 0 && code !== 120) {
     throw new Error(`${file}: exit ${code}`);
```

**Comment by davedoesdev** [comment] 2019-05-27 23:38
And the test is more robust like this:

```diff
diff --git a/test/c/stdin.c b/test/c/stdin.c
index 137a447..1e0c70d 100644
--- a/test/c/stdin.c
+++ b/test/c/stdin.c
@@ -1,10 +1,16 @@
 #include <stdio.h>
+#include <string.h>
 
 int main(void)
 {
     char x[32];
 
-    fgets(x, sizeof x, stdin);
+    if (!fgets(x, sizeof x, stdin)) {
+        return 1;
+    }
+    if (strcmp(x, "foo") != 0) {
+        return 2;
+    }
     fputs(x, stdout);
     return 0;
 }
```

**Comment by devsnek** [comment] 2019-05-27 23:43
fgets returns the first argument, so that will always fail. the stdin test actually passed just fine, but you did inspire me to add stricter checks. https://github.com/devsnek/node-wasi/commit/ea9b49078acdcfeeaa41c0761243d4c5024ec6ec

**Comment by devsnek** [comment] 2019-05-27 23:43
i'm going to close this as working as intended

**Closed as completed by devsnek** 2019-05-27 23:43 UTC
Labels: wontfix
